### ISSUE TITLE
npm run dev后一直加载不出来？

### ISSUE THREAD

**Issue by qiuquanwu** [chenxch/xlegex#1]

**Comment by chenxch** [comment]
有详细信息么？ 如果是字体的话我认为是不太可能哦

**Comment by chenxch** [comment]
能否提供一下详细的信息或者repo？

**Comment by qiuquanwu** [comment]
这个应该是跟系统有关。每个人的系统不一样。谷歌浏览器检测到你引入了本地没有安装的字体资源，他就会从谷歌的服务器去请求远程资源，这个有可能是连接不上。我猜的

**Comment by chenxch** [comment]
> 这个应该是跟系统有关。每个人的系统不一样。谷歌浏览器检测到你引入了本地没有安装的字体资源，他就会从谷歌的服务器去请求远程资源，这个有可能是连接不上。我猜的

后半段是不成立的哦，font-family是会一个个匹配系统是否有对应字体，没有的话是以系统默认字体展示，不存在说去服务器请求字体这种做法的哈。

**Comment by chenxch** [comment]
没有其他问题的话我关闭issue了哈，假期愉快~
