### ISSUE TITLE
如何启动

### ISSUE THREAD

**Issue by wjy9902** [chenxch/xlegex#3]
大佬你好，我刚接触编程不就想问一下，要如何启动游戏，感谢！

**Comment by chenxch** [comment]
你先clone或者下载该项目到本地，然后开始配置前端开发环境，如果已经有开发环境可以先跳过第一步
1、安装nodejs，安装后通过命令台输入`node -v`看是否有打印版本信息，有打印就是安装成功了
2、进入到项目根目录下，执行`npm install` ,如果安装依赖很慢的话你可以百度npm设置淘宝镜像，找日期比较新的文章
3、依赖安装完成后，执行`npm run dev` 项目就会启动了，然后访问http://localhost:5713就可以看到效果了

**Comment by wjy9902** [comment]
谢谢！请问如何像您一样把游戏挂到github让朋友也玩到呢？

**Comment by chenxch** [comment]
> 谢谢！请问如何像您一样把游戏挂到github让朋友也玩到呢？

这个你可以搜索下GitHub Pages哦

**Comment by 451444336** [comment]
上传代码图片显示不了，这是为什么
